# Build settings

markdown: kramdown
permalink: /blog-posts/:title
paginate: 5
paginate_path: '/pagination/page:num/'
port: 8000
url: 'http://0.0.0.0:8000'

include: ['_includes/work']
exclude: ['node_modules']

sass:
  sass_dir: assets/css
  style: :compressed
