# Build settings

markdown: kramdown
permalink: /blog/:title
paginate: 5
paginate_path: '/pagination/page:num/'

port: 8000

include: ['_includes/work']
exclude: ['node_modules']

sass:
  sass_dir: assets/css
  style: :compressed
