#-------------------------------
# General Site Settings

title: Constantin Naumov
description: Front-End Web Developer
email: const.int.naumov@gmail.com
copyright: Constantin Naumov © 2014

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me }
- {name: Portfolio }
- {name: Experience }
- {name: Contact }

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Constantin is all about the web on front of ends.** <br/>
  He used to deliver user experience as technology masterpiece. He know the value of making emotional UI stuff well designed for backend coders.

skills:
- {name: JavaScript Programming, value: '7'}
- {name: Responsive Layouting, value: '8'}
- {name: CSS3 Animations, value: '9'}
- {name: UX Design, value: '5'}
- {name: Learning, value: '10'}
- {name: Communication, value: '6'}

#-------------------------------
# Work Section

projects:
- {url: google.ru, name: ennoaeao.py , folder: 'proj-1', file: 'work/proj-1.html'}
- {url: google.ru, name: City-IN website , folder: 'proj-2', file: 'work/proj-2.html'}
- {url: google.ru, name: Crispy Icons, folder: 'proj-3', file: 'work/proj-3.html'}
- {url: google.ru, name: Flat Mobile , folder: 'proj-4', file: 'work/proj-4.html'}
- {url: google.ru, name: Fresh It Up, folder: 'proj-5', file: 'work/proj-5.html'}
- {url: google.ru, name: Timeline Page, folder: 'proj-6', file: 'work/proj-6.html'}
- {url: google.ru, name: Weather Dashboard, folder: 'proj-7', file: 'work/proj-7.html'}
- {url: google.ru, name: Stripes , folder: 'proj-8', file: 'work/proj-8.html'}




#-------------------------------
# Clients Section

clients:
- {content: '<div class="phone-screen html-section"> <div class="phone-header"><div class="icon-search"></div> <div class="phone-menu"></div></div><div class="phone-post" id="first-post"> <div class="post-thumb"></div><div class="line post-title-1"></div><div class="line post-title-2"></div><div class="line post-line-1"></div><div class="line post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div></div>',
  title: 'Making troubleproof layouts',
  quote: "Human readability and semantics of resulting code are powered by <a href='http://gruntjs.com/' target='_blank'>frontend toolboxes</a> and <a href='http://jekyllrb.com' target='_blank'>template engines</a>. <br /> Well formed pages are to be produced on every iteration of employer's development lifecycle.",
  logo: 'HTML'}
- {content: '<div class="phone-screen css-section"> <div class="phone-header"> <div class="icon-search"></div> <div class="phone-menu"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="line post-title-1"></div><div class="line post-title-2"></div><div class="line post-line-1"></div><div class="line post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="line post-title-1"></div><div class="line post-title-2"></div><div class="line post-line-1"></div><div class="line post-line-2"></div></div> <div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div></div>',
  title: 'Making troubleproof layouts',
  quote: "Human readability and semantics of resulting code are powered by modern frontend toolboxes and template engines. Well formed pages are to be produced on every iteration of employer's development lifecycle.",
  logo: 'CSS'}
- {content: '<div class="phone-screen js-section"> <div class="phone-header"> <div class="icon-search"></div> <div class="phone-menu"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="line post-title-1"></div><div class="line post-title-2"></div><div class="line post-line-1"></div><div class="line post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="line post-title-1"></div><div class="line post-title-2"></div><div class="line post-line-1"></div><div class="line post-line-2"></div></div> <div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div><div class="phone-post"> <div class="post-thumb"></div><div class="post-title-1"></div><div class="post-title-2"></div><div class="post-line-1"></div><div class="post-line-2"></div></div></div>',
  title: 'Making troubleproof layouts',
  quote: "Human readability and semantics of resulting code are powered by modern frontend toolboxes and template engines. Well formed pages are to be produced on every iteration of employer's development lifecycle.",
  logo: 'JS'}
- {content: 'vector.png',
  title: 'Making troubleproof layouts',
  quote: "Human readability and semantics of resulting code are powered by modern frontend toolboxes and template engines. Well formed pages are to be produced on every iteration of employer's development lifecycle.",
  logo: 'SVG'}
- {content: 'wp.png',
  title: 'Making troubleproof layouts',
  quote: "Human readability and semantics of resulting code are powered by modern frontend toolboxes and template engines. Well formed pages are to be produced on every iteration of employer's development lifecycle.",
  logo: 'CMS'}
- {content: 'php.png',
  title: 'Making troubleproof layouts',
  quote: "Human readability and semantics of resulting code are powered by modern frontend toolboxes and template engines. Well formed pages are to be produced on every iteration of employer's development lifecycle.",
  logo: 'PHP'}


#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/Const_Naumov'}
- {icon: 'github', link: 'https://github.com/const-int'}
- {icon: 'linkedin', link: 'http://ru.linkedin.com/pub/konstantin-naumov/a1/847/b33/'}

