#-------------------------------
# General Site Settings

title: Konstantin Naumov
description: Константин Наумов
subdescription: фронтенд разработчик
email: const.int.naumov@gmail.com
copyright: Konstantin Naumov © 2014


menu:
- {name: Блог, hash: '#blog' }
- {name: Обо мне, hash: '#about' }
- {name: Портфолио, hash: '#portfolio' }
- {name: Мои навыки, hash: '#experience' }
- {name: Контакты, hash: '#contact' }

#-------------------------------
# SEO Section

seo:
  description: 'Константин Наумов, фронтенд разработчик'

#-------------------------------
# Titles

section-titles:
  about: "Пара слов про меня"
  portfolio: "Мои последние работы"
  experience: "Основные навыки"
  contact: "Пишите мне"
  blog: 'Блог про'

#-------------------------------
# About Section

blurb: >
  Я люблю создавать красивые и удобные интерфейсы, которые потом нравится людям.
  При этом я учитываю потребности серверных разработчиков и не усложняю им жизнь, так как забочусь о ясности и эффективности кода.
  Меня интересуют

blurb2: >
  Вы можете ознакомиться с моими <a href="#experience">навыками</a>, а также недавними <a href="#portfolio">проектами</a>.<br>
  Если заинтересованы в сотрудничестве, то со мной легко связаться.

contact:
  "Я пишу об интересных мне вещах в [Twitter](https://twitter.com/Const_Naumov).
  Некоторые мои проекты можно посмотреть на [GitHub](https://github.com/const-int).
  Также я регулярно размещаю свои поделки на [CodePen](http://codepen.io/const-int/).
  <br>Вы всегда можете связаться со мной по почте и я постараюсь ответить вам в кратчайшие сроки."

skills:
- { name: 'Адаптивная верстка'      ,  desc: 'Разработка для всех устройств', value: '9', icon: 'icon-responsive' }
- { name: 'Программирование'        ,  desc: 'Функционал клиенткой части',        value: '6', icon: 'icon-tag'        }
- { name: 'Дизайн интерфейсов'      ,  desc: 'Актуальные тренды и стандарты',     value: '5', icon: 'icon-tools'      }
- { name: 'Новинки веб технологий'  ,  desc: 'Использование современных API',     value: '8', icon: 'icon-browser'    }



#-------------------------------
# Blog Section

categories:
- {name: веб-дизайн, hash: 'web' }
- {name: интересное, hash: 'highlight' }
- {name: меня, hash: 'life' }


#-------------------------------
# Work Section

projects:
- {url: '', name: 'Корпоративный сайт' }
- {url: 'teatrpodarkov.ru', name: 'Онлайн магазин' }
- {url: 'const.in/stego/', name: 'Крипто-приложение' }
- {url: '', name: 'Онлайн магазин' }
- {url: 'karavan39.ru/fotoshtory', name: 'Продающая страница' }
- {url: 'web-sendbox.tk/slk-service', name: 'Онлайн магазин' }
- {url: 'plektra.pro/', name: 'Сайт агенства' }
- {url: 'sukho.ru', name: 'Продающая страница' }
- {url: 'const.in/lottery/', name: 'Продающая страница' }




#-------------------------------
# Clients Section

exps:
- {file: 'exp/exp_html.html',
  quote: "Главное для меня это создание кросс-браузерной верстки без неожиданных артефактов. Я превращаю макеты в хорошо скомпонованные страницы и подстраиваюсь под бизнес процессы заказчика. <br>Читаемость кода и соответствие семантике поддерживаю при помощи различных <a href='http://gruntjs.com/'>инструментов компановки</a> и <a href='http://jade-lang.com/'>шаблонизаторов</a>.",
  title: 'Создание качественной разметки'}
- {file: 'exp/exp_css.html',
  quote: 'Таблицы стилей - неотъемлемая часть жизненного цикла веб проекта, они же и представляют наибольшую сложность в фронтенд разработке.<br> Для поддержания целостности и единства во всех браузерах на всех устройствах используется множество трюков, с большинством из которых я знаком и применяю на практике. <a href="http://sass-lang.com/">Препроцессоры</a> и <a href="http://bourbon.io/">примеси</a> использую повсеместно, а если проект достаточно большой, то нахожу разумным использование <a href="http://compass-style.org/">CSS фреймворков</a>.',
  title: 'Кросс-браузерная стилизация'}
- {file: 'exp/exp_svg.html',
  quote: "Количество дисплеев с высоким разрешением неуклонно растет и вместе с ними требования в графике. Вектор не только позволяет получать кристально четкий результат на любом дисплее, но и упрощает анимацию, не требуя специальной поддержки конкретных браузеров. <br> В основоном я применяю SVG при разработке мобильных версиий и создии эффектов с помошью <a href='http://snapsvg.io/'>JS библиотек.</a>",
  title: 'Манипуляции векторными элементами'}
- {file: 'exp/exp_js.html',
  quote: "JavaScript – это мой основной инструмент при создании интерактивности. <br> Я достаточно компетентен с DOM и jQuery и без труда управляю любыми элементами веб страницы. Недавно начал использовать <a href='http://coffeescript.org/'>CoffeeScript</a> и буду продолжать дальше.",
  title: 'Прораммирование на JavaScript'}
- {file: 'exp/exp_cms.html',
  quote: "Хоть для меня фронтенд разработка является основной, иногда приходится выполнять простые задачи по бекенду, вроде создания шаблона для WordPress и т.п. <br> Также мне очень понравились статические сайто-генераторы <a href='http://jekyllrb.com/'>Jekyll</a> и <a href='https://middlemanapp.com/'>Middleman</a>",
  title: 'Шаблонизация и настройка CMS'}
- {file: 'exp/exp_ajax.html',
  quote: "Я всегда стараюсь создавать комфорт для пользователя. Это заключается в превращении красивого дизайна в удобный и работающий продукт.",
  title: 'Аналитика и модернизация UX'}


#-------------------------------
# Contact Section

contacts:
- {name: 'linkedin', link: 'http://ru.linkedin.com/pub/konstantin-naumov/a1/847/b33/' }
- {name: 'github', link: 'http://twitter.com/Const_Naumov' }
- {name: 'twitter', link: 'http://github.com/const-int' }
- {name: 'email', link: 'mailto:const.int.naumov@gmail.com' }

